/**
 * E2E test environment constants.
 * These values are generated by `npm run seed:e2e` in guiders-backend.
 * If the backend team resets the database, new values will be provided.
 */
export const E2E = {
  companyId: '19896f02-febb-4e44-84b9-91e957644f20',
  siteId: '3cc4c92e-2f52-46b5-99b6-f898935f950d',
  domain: 'e2e.guiders.local',
  adminEmail: 'e2e-admin@guiders.test',
  adminPassword: 'E2eAdmin123!',
  apiKey: '40c7f31e1f9b278444500e213086e0aa82865206d3d74a41926c12cc026a762f',

  /** Total visitors seeded in the E2E environment. */
  totalVisitors: 150,
  /** Batch size used by the visitors component (batchSize input). */
  batchSize: 25,
};
