# Workflow para deployment de Angular SSR a producción usando GitHub Environments
# .github/workflows/deploy.yml
name: Deploy Angular SSR to Production

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar manualmente
    inputs:
      force_deploy:
        description: 'Forzar deployment (skip some checks)'
        required: false
        default: false
        type: boolean

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: deploy
    
    env:
      NODE_VERSION: '20'
      SSH_HOST: '10.8.0.1'
      SSH_USER: 'root'
      DEPLOY_PATH: '/var/www/guiders'
      BACKUP_PATH: '/tmp/guiders-backup'

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 📦 Install root dependencies
        run: npm ci --legacy-peer-deps

      - name: 📦 Install Guiders-20 dependencies
        run: |
          cd guiders-20
          npm ci --legacy-peer-deps

      - name: 🏗️ Build Angular SSR application
        run: |
          cd guiders-20
          npm run build:prod:env

      - name: 📁 Verify build output
        run: |
          echo "Verificando estructura de build..."
          ls -la guiders-20/dist/
          if [ -d "guiders-20/dist/guiders-20" ]; then
            echo "✅ Build exitoso"
            echo "📁 Contenido del build:"
            ls -la guiders-20/dist/guiders-20/
            if [ -d "guiders-20/dist/guiders-20/browser" ]; then
              echo "✅ Cliente (browser) generado"
              ls -la guiders-20/dist/guiders-20/browser/ | head -10
            fi
            if [ -d "guiders-20/dist/guiders-20/server" ]; then
              echo "✅ Servidor (SSR) generado"
              ls -la guiders-20/dist/guiders-20/server/ | head -10
              # Verificar que server.mjs existe
              if [ -f "guiders-20/dist/guiders-20/server/server.mjs" ]; then
                echo "✅ server.mjs encontrado"
              else
                echo "❌ Error: server.mjs no encontrado"
                exit 1
              fi
            else
              echo "❌ Error: No se encontró el directorio server"
              exit 1
            fi
          else
            echo "❌ Error: No se encontró el directorio de build"
            exit 1
          fi

      - name: 🔒 Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn sshpass

      - name: 🔧 Setup OpenVPN config
        run: |
          echo "${{ secrets.OVPN_CONFIG }}" > vpn.conf
          chmod 600 vpn.conf

      - name: 🌐 Connect to VPN
        run: |
          sudo openvpn --config vpn.conf --daemon
          sleep 20
          echo "🔍 Verificando conexión VPN..."
          ping -c 3 ${{ env.SSH_HOST }} || echo "⚠️ Ping falló, continuando..."

      - name: 🔑 Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: 🧪 Test SSH connection
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} \
            "echo '✅ Conexión SSH exitosa'"

      - name: 🛡️ Create backup of current deployment
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} << 'EOF'
            # Crear backup con timestamp
            TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
            BACKUP_DIR="${{ env.BACKUP_PATH }}_${TIMESTAMP}"
            
            echo "📦 Creando backup en ${BACKUP_DIR}..."
            
            if [ -d "${{ env.DEPLOY_PATH }}" ]; then
              mkdir -p "${BACKUP_DIR}"
              cp -r ${{ env.DEPLOY_PATH }}/* "${BACKUP_DIR}/" || true
              echo "✅ Backup creado exitosamente"
              
              # Mantener solo los últimos 5 backups
              ls -dt ${{ env.BACKUP_PATH }}_* | tail -n +6 | xargs rm -rf || true
            else
              echo "⚠️ No existe deployment anterior, creando directorio..."
              mkdir -p ${{ env.DEPLOY_PATH }}
            fi
          EOF

      - name: 🛠️ Prepare server environment
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} << 'EOF'
            # Esperar un momento para evitar conflictos con actualizaciones del OS
            echo "⏳ Esperando estabilización del sistema..."
            sleep 30
            
            # Verificar/instalar Node.js si no existe
            if ! command -v node &> /dev/null; then
              echo "📥 Instalando Node.js..."
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            
            # Verificar versión de Node.js
            echo "🟢 Node.js version: $(node --version)"
            echo "📦 NPM version: $(npm --version)"
            
            # Crear directorios necesarios
            mkdir -p ${{ env.DEPLOY_PATH }}/dist
            mkdir -p ${{ env.DEPLOY_PATH }}/logs
            
            # Instalar PM2 si no existe (para gestión de procesos)
            if ! command -v pm2 &> /dev/null; then
              echo "⚡ Instalando PM2..."
              npm install -g pm2
            fi
            
            echo "🟢 PM2 version: $(pm2 --version)"
          EOF

      - name: 🚀 Deploy Angular SSR application
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          echo "🚀 Iniciando deployment..."
          
          # Sync del build completo (cliente + servidor)
          sshpass -p "$SSH_PASSWORD" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --progress \
            guiders-20/dist/guiders-20/ \
            ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/dist/
          
          echo "✅ Archivos sincronizados exitosamente"

      - name: 📋 Deploy package.json and dependencies
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Copiar package.json y package-lock.json para las dependencias de producción
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
            guiders-20/package.json \
            ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
          
          # Copiar package-lock.json si existe
          if [ -f guiders-20/package-lock.json ]; then
            sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
              guiders-20/package-lock.json \
              ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
            echo "✅ package.json y package-lock.json copiados"
          else
            echo "⚠️ package-lock.json no encontrado, solo package.json copiado"
          fi

      - name: 🔧 Install production dependencies
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} << 'EOF'
            cd ${{ env.DEPLOY_PATH }}
            echo "📦 Instalando dependencias de producción..."
            
            # Verificar que package.json existe
            if [ ! -f package.json ]; then
              echo "❌ Error: package.json no encontrado"
              exit 1
            fi
            
            # Instalar dependencias con fallback
            if [ -f package-lock.json ]; then
              npm ci --only=production --omit=dev --legacy-peer-deps
            else
              echo "⚠️ package-lock.json no encontrado, usando npm install"
              npm install --only=production --legacy-peer-deps
            fi
            
            echo "✅ Dependencias instaladas"
          EOF

      - name: 🔄 Deploy PM2 ecosystem configuration
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Copiar archivo ecosystem.config.js predefinido al servidor
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
            .github/ecosystem.config.js \
            ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
          
          echo "✅ Archivo PM2 ecosystem copiado al servidor"

      - name: ⚡ Start/Restart Angular SSR server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} << 'EOF'
            cd ${{ env.DEPLOY_PATH }}
            
            echo "🔄 Gestionando aplicación PM2..."
            
            # Verificar que el archivo server.mjs existe
            if [ ! -f "./dist/server/server.mjs" ]; then
              echo "❌ Error: ./dist/server/server.mjs no encontrado"
              echo "📁 Contenido de ./dist/:"
              ls -la ./dist/
              if [ -d "./dist/server/" ]; then
                echo "📁 Contenido de ./dist/server/:"
                ls -la ./dist/server/
              fi
              exit 1
            fi
            
            # Detener aplicación existente de forma segura
            if pm2 list | grep -q "guiders-ssr"; then
              echo "🛑 Deteniendo aplicación existente..."
              pm2 stop guiders-ssr || echo "⚠️ No se pudo detener la aplicación"
              pm2 delete guiders-ssr || echo "⚠️ No se pudo eliminar la aplicación"
            else
              echo "ℹ️ No hay aplicación PM2 previa ejecutándose"
            fi
            
            # Limpiar procesos PM2 si es necesario
            pm2 kill || echo "ℹ️ No había procesos PM2 para limpiar"
            
            # Esperar un momento para que los procesos se liberen
            sleep 3
            
            # Iniciar aplicación
            echo "🚀 Iniciando aplicación..."
            pm2 start ecosystem.config.js --env production
            
            # Guardar configuración PM2
            pm2 save
            
            # Configurar PM2 para arranque automático
            pm2 startup || echo "⚠️ No se pudo configurar startup automático"
            
            echo "✅ Aplicación iniciada con PM2"
            echo "📊 Estado de la aplicación:"
            pm2 status
            
            # Esperar a que la aplicación arranque
            echo "⏳ Esperando que la aplicación arranque..."
            sleep 10
            
            # Verificar que la aplicación está respondiendo
            echo "🔍 Verificando respuesta de la aplicación..."
            for i in {1..6}; do
              if curl -f -s http://localhost:4000 > /dev/null 2>&1; then
                echo "✅ Aplicación respondiendo correctamente en puerto 4000"
                break
              else
                echo "⏳ Intento $i/6 - Esperando respuesta del servidor..."
                sleep 5
              fi
            done
            
            # Mostrar logs recientes si hay problemas
            if ! curl -f -s http://localhost:4000 > /dev/null 2>&1; then
              echo "⚠️ La aplicación no responde, mostrando logs:"
              pm2 logs guiders-ssr --lines 20 --nostream || echo "No se pudieron obtener los logs"
            fi
          EOF

      - name: 🧹 Cleanup and final verification
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Copiar script de verificación al servidor
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
            .github/verify-deployment.sh \
            ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
          
          # Ejecutar verificación post-deployment
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} << 'EOF'
            cd ${{ env.DEPLOY_PATH }}
            chmod +x verify-deployment.sh
            ./verify-deployment.sh
          EOF

      - name: 🎉 Deployment Summary
        run: |
          echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Build**: Angular SSR aplicación compilada" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Deploy**: Archivos sincronizados a servidor" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Dependencies**: Dependencias de producción instaladas" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Server**: Aplicación SSR iniciada con PM2" >> $GITHUB_STEP_SUMMARY
          echo "- 🌐 **URL**: http://${{ env.SSH_HOST }}:4000" >> $GITHUB_STEP_SUMMARY
          echo "- 🏷️ **Environment**: deploy" >> $GITHUB_STEP_SUMMARY
          echo "- 📅 **Deployed at**: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "- 🔗 **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📊 Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "- Verificar que la aplicación responde correctamente" >> $GITHUB_STEP_SUMMARY
          echo "- Configurar proxy reverso (Nginx) si es necesario" >> $GITHUB_STEP_SUMMARY
          echo "- Configurar SSL/HTTPS" >> $GITHUB_STEP_SUMMARY

      - name: 📢 Update Deployment Status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const deploymentState = '${{ job.status }}' === 'success' ? 'success' : 'failure';
            const description = '${{ job.status }}' === 'success' 
              ? '✅ Deployment completado exitosamente' 
              : '❌ Deployment falló';
            
            // Crear deployment status
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: context.payload.deployment?.id || 0,
              state: deploymentState,
              description: description,
              environment: 'deploy',
              environment_url: 'http://${{ env.SSH_HOST }}:4000'
            });
            
            console.log(`Deployment status updated: ${deploymentState}`);
