# Workflow para deployment de Angular SSR a producción usando GitHub Environments
# .github/workflows/deploy.yml
name: Deploy Angular SSR to Production

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar manualmente
    inputs:
      force_deploy:
        description: 'Forzar deployment (skip some checks)'
        required: false
        default: false
        type: boolean

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: deploy
    
    env:
      NODE_VERSION: '20'
      SSH_HOST: '10.8.0.1'
      SSH_USER: 'root'
      DEPLOY_PATH: '/var/www/guiders'
      BACKUP_PATH: '/tmp/guiders-backup'

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 📦 Install root dependencies
        run: npm ci --legacy-peer-deps

      - name: 📦 Install Guiders-20 dependencies
        run: |
          cd guiders-20
          npm ci --legacy-peer-deps

      - name: 🏗️ Build Angular SSR application
        run: |
          cd guiders-20
          npm run build:prod:env

      - name: 📁 Verify build output
        run: |
          echo "Verificando estructura de build..."
          ls -la guiders-20/dist/
          
          # Verificar estructura Angular 20 (siempre tiene el subdirectorio del proyecto)
          if [ -d "guiders-20/dist/guiders-20" ]; then
            echo "✅ Build exitoso - encontrado subdirectorio del proyecto"
            echo "📁 Contenido del build principal:"
            ls -la guiders-20/dist/guiders-20/
            
            # Verificar que existen las carpetas browser y server
            if [ -d "guiders-20/dist/guiders-20/browser" ] && [ -d "guiders-20/dist/guiders-20/server" ]; then
              echo "✅ Directorios browser y server encontrados"
              
              echo "📁 Contenido del cliente (browser):"
              ls -la guiders-20/dist/guiders-20/browser/ | head -10
              
              echo "📁 Contenido del servidor (server):"
              ls -la guiders-20/dist/guiders-20/server/ | head -10
              
              # Verificar que server.mjs existe
              if [ -f "guiders-20/dist/guiders-20/server/server.mjs" ]; then
                echo "✅ server.mjs encontrado"
              else
                echo "❌ Error: server.mjs no encontrado"
                echo "📁 Archivos en server/:"
                ls -la guiders-20/dist/guiders-20/server/
                exit 1
              fi
              
              # Verificar index.html en browser (puede tener diferentes nombres)
              if [ -f "guiders-20/dist/guiders-20/browser/index.csr.html" ] || [ -f "guiders-20/dist/guiders-20/browser/index.html" ]; then
                echo "✅ Archivo index HTML encontrado en el cliente"
              else
                echo "❌ Error: No se encontró archivo index HTML en el cliente"
                echo "📁 Archivos HTML en browser/:"
                ls -la guiders-20/dist/guiders-20/browser/*.html 2>/dev/null || echo "No se encontraron archivos HTML"
                exit 1
              fi
            else
              echo "❌ Error: No se encontraron directorios browser/server"
              echo "📁 Contenido disponible:"
              ls -la guiders-20/dist/guiders-20/
              exit 1
            fi
          else
            echo "❌ Error: No se encontró el subdirectorio del proyecto en dist/"
            echo "📁 Explorando estructura completa:"
            find guiders-20/dist/ -type d 2>/dev/null | head -10
            echo ""
            echo "📁 Buscando archivos importantes:"
            find guiders-20/dist/ -name "server.mjs" -o -name "*.html" -o -name "main*.js" 2>/dev/null | head -10
            exit 1
          fi

      - name: 🔒 Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn sshpass

      - name: 🔧 Setup OpenVPN config
        run: |
          echo "${{ secrets.OVPN_CONFIG }}" > vpn.conf
          chmod 600 vpn.conf

      - name: 🌐 Connect to VPN
        run: |
          sudo openvpn --config vpn.conf --daemon
          sleep 20
          echo "🔍 Verificando conexión VPN..."
          ping -c 3 ${{ env.SSH_HOST }} || echo "⚠️ Ping falló, continuando..."

      - name: 🔑 Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: 🧪 Test SSH connection
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} \
            "echo '✅ Conexión SSH exitosa'"

      - name: 🛡️ Create backup of current deployment
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} << 'EOF'
            # Crear backup con timestamp
            TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
            BACKUP_DIR="${{ env.BACKUP_PATH }}_${TIMESTAMP}"
            
            echo "📦 Creando backup en ${BACKUP_DIR}..."
            
            if [ -d "${{ env.DEPLOY_PATH }}" ]; then
              mkdir -p "${BACKUP_DIR}"
              cp -r ${{ env.DEPLOY_PATH }}/* "${BACKUP_DIR}/" || true
              echo "✅ Backup creado exitosamente"
              
              # Mantener solo los últimos 5 backups
              ls -dt ${{ env.BACKUP_PATH }}_* | tail -n +6 | xargs rm -rf || true
            else
              echo "⚠️ No existe deployment anterior, creando directorio..."
              mkdir -p ${{ env.DEPLOY_PATH }}
            fi
          EOF

      - name: 🛠️ Prepare server environment
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} << 'EOF'
            # Esperar un momento para evitar conflictos con actualizaciones del OS
            echo "⏳ Esperando estabilización del sistema..."
            sleep 30
            
            # Verificar/instalar Node.js si no existe
            if ! command -v node &> /dev/null; then
              echo "📥 Instalando Node.js..."
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            
            # Verificar versión de Node.js
            echo "🟢 Node.js version: $(node --version)"
            echo "📦 NPM version: $(npm --version)"
            
            # Crear directorios necesarios
            mkdir -p ${{ env.DEPLOY_PATH }}/dist
            mkdir -p ${{ env.DEPLOY_PATH }}/logs
            
            # Instalar PM2 si no existe (para gestión de procesos)
            if ! command -v pm2 &> /dev/null; then
              echo "⚡ Instalando PM2..."
              npm install -g pm2
            fi
            
            echo "🟢 PM2 version: $(pm2 --version)"
          EOF

      - name: 🚀 Deploy Angular SSR application
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          echo "🚀 Iniciando deployment..."
          
          # Sync del build completo (cliente + servidor)
          sshpass -p "$SSH_PASSWORD" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --progress \
            guiders-20/dist/guiders-20/ \
            ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/dist/
          
          echo "✅ Archivos sincronizados exitosamente"

      - name: 📋 Deploy package.json and dependencies
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Copiar package.json y package-lock.json para las dependencias de producción
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
            guiders-20/package.json \
            ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
          
          # Copiar package-lock.json si existe
          if [ -f guiders-20/package-lock.json ]; then
            sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
              guiders-20/package-lock.json \
              ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
            echo "✅ package.json y package-lock.json copiados"
          else
            echo "⚠️ package-lock.json no encontrado, solo package.json copiado"
          fi

      - name: 🔧 Install production dependencies
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} << 'EOF'
            cd ${{ env.DEPLOY_PATH }}
            echo "📦 Instalando dependencias de producción..."
            
            # Verificar que package.json existe
            if [ ! -f package.json ]; then
              echo "❌ Error: package.json no encontrado"
              exit 1
            fi
            
            # Instalar dependencias con fallback
            if [ -f package-lock.json ]; then
              npm ci --only=production --omit=dev --legacy-peer-deps
            else
              echo "⚠️ package-lock.json no encontrado, usando npm install"
              npm install --only=production --legacy-peer-deps
            fi
            
            echo "✅ Dependencias instaladas"
          EOF

      - name: 🔄 Deploy PM2 ecosystem and management scripts
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Copiar archivo ecosystem.config.js predefinido al servidor
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
            .github/ecosystem.config.js \
            ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
          
          # Copiar script de gestión segura de PM2
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
            .github/pm2-safe-management.sh \
            ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
          
          echo "✅ Archivos PM2 ecosystem y script de gestión copiados al servidor"

      - name: 🗄️ Deploy database cleanup scripts
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          echo "📦 Copiando scripts de limpieza de base de datos al servidor..."
          
          # Copiar script principal de limpieza basado en entidades
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
            clean-database-entities.sh \
            ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
          
          # Copiar script de limpieza general
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
            clean-database.sh \
            ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
          
          # Copiar documentación y guías
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
            DATABASE-CLEANUP-README.md \
            ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
          
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
            PRODUCTION-DATABASE-CLEANUP-GUIDE.md \
            ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
          
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
            SERVIDOR-PRODUCCION-PASOS.md \
            ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
          
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
            QUICK-START-CLEANUP.md \
            ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
          
          # Hacer los scripts ejecutables en el servidor
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} << 'EOF'
            cd ${{ env.DEPLOY_PATH }}
            chmod +x clean-database-entities.sh
            chmod +x clean-database.sh
            echo "✅ Scripts de limpieza de base de datos configurados y ejecutables"
          EOF
          
          echo "✅ Scripts de limpieza de base de datos desplegados exitosamente"

      - name: ⚡ Start/Restart Angular SSR server (Safe PM2 Management)
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        timeout-minutes: 10
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ServerAliveInterval=10 -o ServerAliveCountMax=3 ${{ env.SSH_USER }}@${{ env.SSH_HOST }} << 'EOF'
            cd ${{ env.DEPLOY_PATH }}
            
            echo "🔄 Gestionando aplicación PM2 de forma segura..."
            
            # Verificar estructura del deployment
            echo "📁 Verificando estructura del deployment..."
            ls -la ./dist/
            
            # Verificar que el archivo server.mjs existe
            if [ ! -f "./dist/server/server.mjs" ]; then
              echo "❌ Error: ./dist/server/server.mjs no encontrado"
              echo "📁 Contenido completo de ./dist/:"
              find ./dist/ -type f -name "*.mjs" -o -name "*.js" | head -10
              echo ""
              echo "📁 Buscando server.mjs en cualquier ubicación:"
              find ./dist/ -name "server.mjs" -type f
              exit 1
            fi
            
            echo "✅ server.mjs encontrado, procediendo con PM2..."
            
            # Hacer el script ejecutable
            chmod +x pm2-safe-management.sh
            
            # Reinicio simple y directo con timeouts
            echo "🔄 Deteniendo aplicación anterior si existe..."
            timeout 20 pm2 stop guiders-ssr 2>/dev/null || echo "⚠️ No había aplicación anterior corriendo"
            timeout 15 pm2 delete guiders-ssr 2>/dev/null || echo "⚠️ No había aplicación anterior para eliminar"
            
            echo "🚀 Iniciando nueva aplicación..."
            if timeout 30 pm2 start ecosystem.config.js --env production; then
              echo "✅ Aplicación iniciada con PM2"
              
              # Verificar que está corriendo
              sleep 5
              if timeout 10 pm2 list | grep -q "guiders-ssr.*online"; then
                echo "✅ Aplicación está corriendo correctamente"
                
                # Guardar configuración
                timeout 10 pm2 save || echo "⚠️ No se pudo guardar la configuración PM2"
                
                # Estado final
                echo "📊 Estado final:"
                timeout 10 pm2 status || echo "⚠️ No se pudo mostrar el estado"
              else
                echo "❌ La aplicación no está corriendo después del inicio"
                timeout 10 pm2 logs guiders-ssr --lines 10 --nostream || echo "⚠️ No se pudieron mostrar los logs"
                exit 1
              fi
            else
              echo "❌ Error al iniciar la aplicación con PM2"
              exit 1
            fi
          EOF

      # - name: 🧹 Cleanup and final verification
      #   env:
      #     SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      #   run: |
      #     # Copiar script de verificación segura al servidor
      #     sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no \
      #       .github/verify-deployment-safe.sh \
      #       ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DEPLOY_PATH }}/
          
      #     # Ejecutar verificación post-deployment segura
      #     sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} << 'EOF'
      #       cd ${{ env.DEPLOY_PATH }}
      #       chmod +x verify-deployment-safe.sh
      #       ./verify-deployment-safe.sh
      #     EOF

      - name: 🎉 Deployment Summary
        run: |
          echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Build**: Angular SSR aplicación compilada" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Deploy**: Archivos sincronizados a servidor" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Dependencies**: Dependencias de producción instaladas" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Server**: Aplicación SSR iniciada con PM2" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ **Database Scripts**: Scripts de limpieza de BD desplegados" >> $GITHUB_STEP_SUMMARY
          echo "- 🌐 **URL**: http://${{ env.SSH_HOST }}:4000" >> $GITHUB_STEP_SUMMARY
          echo "- 🏷️ **Environment**: deploy" >> $GITHUB_STEP_SUMMARY
          echo "- 📅 **Deployed at**: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "- 🔗 **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📊 Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "- Verificar que la aplicación responde correctamente" >> $GITHUB_STEP_SUMMARY
          echo "- Configurar proxy reverso (Nginx) si es necesario" >> $GITHUB_STEP_SUMMARY
          echo "- Configurar SSL/HTTPS" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🗄️ Database Management" >> $GITHUB_STEP_SUMMARY
          echo "Scripts de limpieza de base de datos disponibles en el servidor:" >> $GITHUB_STEP_SUMMARY
          echo "- \`./clean-database-entities.sh --analyze-only\` - Analizar tablas" >> $GITHUB_STEP_SUMMARY
          echo "- \`./clean-database-entities.sh\` - Limpiar base de datos" >> $GITHUB_STEP_SUMMARY
          echo "- Ver guías: \`DATABASE-CLEANUP-README.md\`, \`SERVIDOR-PRODUCCION-PASOS.md\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "⚠️ **Importante**: Crear backup antes de usar scripts de limpieza" >> $GITHUB_STEP_SUMMARY
